/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_woo_threedimensionremoteserver_RemoteJNI */

#ifndef _Included_com_woo_threedimensionremoteserver_RemoteJNI
#define _Included_com_woo_threedimensionremoteserver_RemoteJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    initVirtualMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_initVirtualMouse
  (JNIEnv *, jobject);

/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    setMoveRel
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_setMoveRel
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    setLeftClick
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_setLeftClick
  (JNIEnv *, jobject);

/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    setRightClick
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_setRightClick
  (JNIEnv *, jobject);

/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    setAcurracy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_setAcurracy
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_woo_threedimensionremoteserver_RemoteJNI
 * Method:    closeVirtualMouse
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_woo_threedimensionremoteserver_RemoteJNI_closeVirtualMouse
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
